A sript that compiles a pythons script file in a variable

diff --git a/0x00-python-hello_world/101-compile b/0x00-python-hello_world/101-compile
--- a/0x00-python-hello_world/101-compile
+++ b/0x00-python-hello_world/101-compile
@@ -1,6 +1,22 @@
-#!/usr/bin/bash
+#!/bin/bash
+
+if [ -z "$PYFILE" ]; then
+  echo "PYFILE environment variable is not set"
+  exit 1
+fi
+
 python3 -m py_compile "$PYFILE"
+
 BASENAME=$(basename "$PYFILE" .py)
+
 PYCACHE_DIR="__pycache__"
 PYC_FILE=$(ls "$PYCACHE_DIR" | grep "$BASENAME" | grep ".pyc")
-mv "SPYCACHE_DIR/$PYC_FILE" "${BASENAME}c"
+
+if [ -z "$PYC_FILE" ]; then
+  echo "Compiled file not found in __pycache__"
+  exit 1
+fi
+
+mv "$PYCACHE_DIR/$PYC_FILE" "${BASENAME}.pyc"
+
+echo "Compiled file saved as ${BASENAME}.pyc"
